### ISSUE TITLE
Campaign config files point to a private area

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/Production#207]
Many of the .cfg and .ini files in CampaignConfig refer to a private uers's area, such as:
CampaignConfig/mdc2020_beam.cfg:includes = /mu2e/app/users/srsoleti/workDir/Production/CampaignConfig/mdc2020_prolog.cfg
These should be updated to use file sfrom the current SimJob musing

**Comment by sophiemiddleton** [comment]
Yes I'm aware of this. I will get to this next week
